<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'auctiondescriptiontest' => '/AuctionDescriptionTest.php',
                'auctiontest' => '/AuctionTest.php',
                'auctiontitletest' => '/AuctionTitleTest.php',
                'bidcollectiontest' => '/BidCollectionTest.php',
                'bidtest' => '/BidTest.php',
                'createmoneytrait' => '/CreateMoneyTrait.php',
                'createusdtrait' => '/CreateUsdTrait.php',
                'currencytest' => '/CurrencyTest.php',
                'emailtest' => '/EmailTest.php',
                'moneytest' => '/MoneyTest.php',
                'usertest' => '/UserTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
