<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'auctiondescriptiontest' => '/AuctionDescriptionTest.php',
                'auctionhelpertrait' => '/AuctionHelperTrait.php',
                'auctionintervaltest' => '/AuctionIntervalTest.php',
                'auctiontitletest' => '/AuctionTitleTest.php',
                'bidcollectiontest' => '/BidCollectionTest.php',
                'biddingandinstantbuyauctiontest' => '/BiddingAndInstantBuyAuctionTest.php',
                'biddingauctiontest' => '/BiddingAuctionTest.php',
                'bidtest' => '/BidTest.php',
                'currencytest' => '/CurrencyTest.php',
                'emailtest' => '/EmailTest.php',
                'moneyhelpertrait' => '/MoneyHelperTrait.php',
                'moneytest' => '/MoneyTest.php',
                'nicknametest' => '/NicknameTest.php',
                'userhelpertrait' => '/UserHelperTrait.php',
                'usertest' => '/UserTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
