<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'auction' => '/Auction.php',
                'auctiontitle' => '/AuctionTitle.php',
                'mihaeu\\productconfigurator\\bid' => '/Bid.php',
                'mihaeu\\productconfigurator\\currency' => '/Currency.php',
                'mihaeu\\productconfigurator\\money' => '/Money.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
